"""Reference switch configurations for SONiC, Arista EOS and Cisco NX-OS.

The generators render one device from the deterministic wiring plan: routed
interfaces, eBGP to every fabric neighbor, and the RoCE QoS profile (DSCP 26
lossless on one priority with PFC + ECN, CNP on DSCP 48). They are reference
templates to validate in a lab before production, not vendor-certified
configs.
"""

from __future__ import annotations

import json

from .wiring import Device

LANES_PER_CAGE = 8


def port_name(nos: str, dev: Device, index: int) -> str:
    cage, lane = divmod(index, dev.ports_per_cage)
    step = LANES_PER_CAGE // dev.ports_per_cage
    if nos == "sonic":
        return f"Ethernet{cage * LANES_PER_CAGE + lane * step}"
    if nos == "eos":
        return f"Ethernet{cage + 1}/{lane * step + 1}"
    if nos == "nxos":
        return f"Ethernet1/{cage + 1}" if dev.ports_per_cage == 1 else f"Ethernet1/{cage + 1}/{lane + 1}"
    raise ValueError(nos)


def render(nos: str, dev: Device, roce: dict) -> str:
    return {"sonic": _sonic, "eos": _eos, "nxos": _nxos}[nos](dev, roce)


def _max_paths(dev: Device) -> int:
    # Spines and super-spines reach a remote prefix over up to k/2 equal-cost paths.
    return max(1, dev.radix // 2)


def _header(dev: Device, comment: str) -> list[str]:
    return [
        f"{comment} {dev.name}: {dev.role}, plane {dev.plane}, AS {dev.asn}",
        f"{comment} Generated by dcdesigner. Reference template: validate in a lab before production.",
    ]


def _sonic(dev: Device, roce: dict) -> str:
    pri = str(roce["lossless_priority"])
    ecn = roce["ecn"]
    lanes = LANES_PER_CAGE // dev.ports_per_cage
    port, intf = {}, {}
    for p in dev.ports:
        name = port_name("sonic", dev, p.index)
        first = int(name.removeprefix("Ethernet"))
        port[name] = {
            "admin_status": "up",
            "alias": f"etp{p.index}",
            "description": p.description,
            "fec": "rs",
            "lanes": ",".join(str(first + i) for i in range(lanes)),
            "mtu": str(roce["mtu"]),
            "speed": str(dev.port_gbps * 1000),
        }
        intf[name] = {}
        intf[f"{name}|{p.local_ip}/31"] = {}
    names = sorted(port, key=lambda n: int(n.removeprefix("Ethernet")))
    config_db = {
        "DEVICE_METADATA": {"localhost": {"hostname": dev.name, "bgp_asn": str(dev.asn), "type": "LeafRouter"}},
        "LOOPBACK_INTERFACE": {"Loopback0": {}, f"Loopback0|{dev.loopback}/32": {}},
        "PORT": port,
        "INTERFACE": intf,
        "DSCP_TO_TC_MAP": {"AZURE": {str(roce["roce_dscp"]): pri, str(roce["cnp_dscp"]): str(roce["cnp_priority"])}},
        "WRED_PROFILE": {
            "AZURE_LOSSLESS": {
                "ecn": "ecn_all",
                "wred_green_enable": "true",
                "green_min_threshold": str(ecn["kmin_kb"] * 1024),
                "green_max_threshold": str(ecn["kmax_kb"] * 1024),
                "green_drop_probability": str(int(ecn["pmax"] * 100)),
            }
        },
        "PORT_QOS_MAP": {n: {"dscp_to_tc_map": "AZURE", "pfc_enable": pri, "pfcwd_sw_enable": pri} for n in names},
        "QUEUE": {f"{n}|{pri}": {"scheduler": "scheduler.0", "wred_profile": "AZURE_LOSSLESS"} for n in names},
    }
    frr = [*_header(dev, "!"), "!", f"hostname {dev.name}", "!", f"router bgp {dev.asn}"]
    frr += [
        f" bgp router-id {dev.loopback}",
        " bgp bestpath as-path multipath-relax",
        " no bgp ebgp-requires-policy",
        " neighbor FABRIC peer-group",
        " neighbor FABRIC bfd",
    ]
    for p in dev.ports:
        if p.peer_asn is not None:
            frr.append(f" neighbor {p.peer_ip} remote-as {p.peer_asn}")
            frr.append(f" neighbor {p.peer_ip} peer-group FABRIC")
            frr.append(f" neighbor {p.peer_ip} description {p.peer}")
    frr += [
        " !",
        " address-family ipv4 unicast",
        "  redistribute connected route-map LOCAL",
        f"  maximum-paths {_max_paths(dev)}",
        " exit-address-family",
        "!",
        "route-map LOCAL permit 10",
        "!",
    ]
    return (
        "# ---- /etc/sonic/config_db.json (fragment) ----\n"
        + json.dumps(config_db, indent=2, sort_keys=True)
        + "\n\n# ---- /etc/sonic/frr/frr.conf ----\n"
        + "\n".join(frr)
        + "\n"
    )


def _eos(dev: Device, roce: dict) -> str:
    pri = roce["lossless_priority"]
    ecn = roce["ecn"]
    speed = f"{dev.port_gbps}g-{8 // dev.ports_per_cage}"
    out = [*_header(dev, "!"), "!", f"hostname {dev.name}", "!", "service routing protocols model multi-agent", "!"]
    out += [
        f"qos map dscp {roce['roce_dscp']} to traffic-class {pri}",
        f"qos map dscp {roce['cnp_dscp']} to traffic-class {roce['cnp_priority']}",
        "!",
        "interface Loopback0",
        f"   ip address {dev.loopback}/32",
        "!",
    ]
    for p in dev.ports:
        out += [
            f"interface {port_name('eos', dev, p.index)}",
            f"   description {p.description}",
            f"   mtu {roce['mtu'] - 2}",
            f"   speed {speed}",
            "   no switchport",
            f"   ip address {p.local_ip}/31",
            "   qos trust dscp",
            "   priority-flow-control on",
            f"   priority-flow-control priority {pri} no-drop",
            f"   tx-queue {pri}",
            f"      random-detect ecn minimum-threshold {ecn['kmin_kb']} kbytes "
            f"maximum-threshold {ecn['kmax_kb']} kbytes max-mark-probability {int(ecn['pmax'] * 100)}",
            "!",
        ]
    out += [
        f"router bgp {dev.asn}",
        f"   router-id {dev.loopback}",
        f"   maximum-paths {_max_paths(dev)}",
        "   bgp bestpath as-path multipath-relax",
        "   neighbor FABRIC peer group",
        "   neighbor FABRIC bfd",
        "   neighbor FABRIC send-community",
    ]
    for p in dev.ports:
        if p.peer_asn is not None:
            out += [
                f"   neighbor {p.peer_ip} peer group FABRIC",
                f"   neighbor {p.peer_ip} remote-as {p.peer_asn}",
                f"   neighbor {p.peer_ip} description {p.peer}",
            ]
    out += ["   redistribute connected", "!", "end", ""]
    return "\n".join(out)


def _nxos(dev: Device, roce: dict) -> str:
    pri = roce["lossless_priority"]
    ecn = roce["ecn"]
    out = [*_header(dev, "!"), f"hostname {dev.name}", "feature bgp", "feature lldp", "feature bfd", "!"]
    out += [
        "class-map type qos match-all ROCE",
        f"  match dscp {roce['roce_dscp']}",
        "class-map type qos match-all CNP",
        f"  match dscp {roce['cnp_dscp']}",
        "policy-map type qos ROCE_CLASSIFY",
        "  class ROCE",
        f"    set qos-group {pri}",
        "  class CNP",
        f"    set qos-group {roce['cnp_priority']}",
        "policy-map type queuing ROCE_QUEUING",
        f"  class type queuing c-out-8q-q{pri}",
        "    bandwidth remaining percent 60",
        f"    random-detect minimum-threshold {ecn['kmin_kb']} kbytes maximum-threshold {ecn['kmax_kb']} kbytes "
        f"drop-probability {int(ecn['pmax'] * 100)} weight 0 ecn",
        f"  class type queuing c-out-8q-q{roce['cnp_priority']}",
        "    priority level 1",
        "system qos",
        "  service-policy type queuing output ROCE_QUEUING",
        "!",
        "interface loopback0",
        f"  ip address {dev.loopback}/32",
        "!",
    ]
    for p in dev.ports:
        out += [
            f"interface {port_name('nxos', dev, p.index)}",
            f"  description {p.description}",
            f"  mtu {roce['mtu']}",
            "  no switchport",
            f"  ip address {p.local_ip}/31",
            "  priority-flow-control mode on",
            "  service-policy type qos input ROCE_CLASSIFY",
            "  no shutdown",
            "!",
        ]
    out += [
        f"router bgp {dev.asn}",
        f"  router-id {dev.loopback}",
        "  bestpath as-path multipath-relax",
        "  address-family ipv4 unicast",
        "    redistribute direct route-map LOCAL",
        f"    maximum-paths {_max_paths(dev)}",
    ]
    for p in dev.ports:
        if p.peer_asn is not None:
            out += [
                f"  neighbor {p.peer_ip}",
                f"    remote-as {p.peer_asn}",
                f"    description {p.peer}",
                "    bfd",
                "    address-family ipv4 unicast",
            ]
    out += ["!", "route-map LOCAL permit 10", ""]
    return "\n".join(out)
